### ISSUE TITLE
[FR] Implement Controls for [raspberry v3 auto focus

### ISSUE THREAD

**Issue by bstadtler** [The-EG/OctoPrint-CameraSettings#171] opened 2023-05-06 19:51 UTC
**raspberry pi camera autofocus v3

{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}:

**Comment by The-EG** [comment] 2023-05-17 16:47
duplicate of #106

**Closed by The-EG** 2023-05-17 16:47 UTC
Labels: enhancement
