### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by Thegs68** [The-EG/OctoPrint-CameraSettings#65] opened 2022-01-08 17:57 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:
Day-Night V2 for Raspberry Pi Camera, Arducam All-Day Image All-Model Support, IR LED for Low Light and Night Vision, M12 Lens Interchangeable, IR Filter Auto-Switch Programmable, OV5647 5MP 1080P

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "force_key_frame": {
    "type": "button",
    "flags": "write"
  },
  "h264_minimum_qp_value": {
    "type": "int",
    "min": "0",
    "max": "51",
    "step": "1",
    "default": "0",
    "value": "0"
  },
  "h264_maximum_qp_value": {
    "type": "int",
    "min": "0",
    "max": "51",
    "step": "1",
    "default": "0",
    "value": "0"
  }
}

**Comment by The-EG** [comment] 2022-01-08 22:06
This is actually already addressed in the latest pre-release. I guess this might be a hint to finally release that...

duplicate of #62

**Closed by The-EG** 2022-01-08 22:06 UTC
Labels: duplicate, enhancement

**Comment by Thegs68** [comment] 2022-01-08 23:04
Thanks for your prompt reply, I will try the RC.
