### ISSUE TITLE
[FR] Implement Controls for [Iphone X]

### ISSUE THREAD

**Issue by Rikard405** [The-EG/OctoPrint-CameraSettings#214] opened 2024-03-18 21:29 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:Iphone X

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "keep_format": {
    "type": "bool",
    "default": "0",
    "value": "0"
  },
  "sustain_framerate": {
    "type": "bool",
    "default": "0",
    "value": "0"
  },
  "timeout": {
    "type": "int",
    "min": "0",
    "max": "100000",
    "step": "1",
    "default": "0",
    "value": "0"
  },
  "timeout_image_io": {
    "type": "bool",
    "default": "0",
    "value": "0"
  }
}

**Comment by The-EG** [comment] 2024-03-18 21:50
duplicate of #213

**Closed as not planned by The-EG** 2024-03-18 21:50 UTC
Labels: enhancement
