### ISSUE TITLE
[FR] Implement Controls for [Pi Cam 3]

### ISSUE THREAD

**Issue by JasonF-BJSS** [The-EG/OctoPrint-CameraSettings#153] opened 2023-04-13 15:06 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:
picam3 
**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "wide_dynamic_range": {
    "type": "bool",
    "default": "0",
    "value": "0",
    "flags": "grabbed"
  }
}

OctoPrint: 1.8.7
Camera Settings: 0.4.1
Setup process in this thread:
https://community.octoprint.org/t/pi-camera-v3-imx-chipset-based-cameras-not-working/49022/35

**Comment by The-EG** [comment] 2023-04-15 13:27
duplicate of #100

**Closed by The-EG** 2023-04-15 13:27 UTC
Labels: enhancement
