### ISSUE TITLE
[FR] Implement Controls for C920 Logitech

### ISSUE THREAD

**Issue by realmadridsi** [The-EG/OctoPrint-CameraSettings#25] opened 2021-04-30 16:46 UTC
{
  "led1_mode": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Off"
      },
      {
        "value": "1",
        "desc": "On"
      },
      {
        "value": "2",
        "desc": "Blink"
      },
      {
        "value": "3",
        "desc": "Auto"
      }
    ],
    "min": "0",
    "max": "3",
    "default": "3",
    "value": "3"
  },
  "led1_frequency": {
    "type": "int",
    "min": "0",
    "max": "255",
    "step": "1",
    "default": "0",
    "value": "0"
  }
}

**Comment by The-EG** [comment] 2021-04-30 16:58
Hi there, these have already been implemented in the latest release candidate, 0.1.1rc1.

You can update to 0.1.1rc1 by changing to the Release Candidate channel for this plugin in the Software Update settings:
![image](https://user-images.githubusercontent.com/7342077/116700285-9aa9b800-a994-11eb-9e05-ddefe3552a5c.png)

Or you can wait for the next release. After some testing, this will be released into an official release (0.1.1)

duplicate of #22

**Closed** 2021-04-30 16:59 UTC
Labels: duplicate
