### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by wjg57** [The-EG/OctoPrint-CameraSettings#114] opened 2023-03-01 10:39 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:

RaspiCam V1.3 NOIR

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}

**Issue**
I had hoped that the Camera Control Plugin would allow me to set common parameters, in this specific case the value for the color saturation (-sa paramter to uvc_input).

The NoIR RaspiCam has no IR filter, which is really useful when you use human invisible IR light (LEDS) for illumination, but the lack of filters results in a violet tint of the pictures.

To fix that the saturation parameter of the uvc_input mjpeg_player should be set to -100 (no color saturation at all), resulting in a black and white image.

**Comment by The-EG** [comment] 2023-03-03 20:39
duplicate of #106 

> I had hoped that the Camera Control Plugin would allow me to set common parameters, in this specific case the value for the color saturation (-sa paramter to uvc_input).

This plugin allows setting the controls that are exposed through the V4L apis. You can see what your camera supports by looking at the output of `v4l2-ctl --list-ctrls-menus`.

**Closed by The-EG** 2023-03-03 20:39 UTC
Labels: enhancement
