### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by signpeddler** [The-EG/OctoPrint-CameraSettings#116] opened 2023-03-05 05:55 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:

https://www.amazon.com/dp/B07SN8HB1R?psc=1&ref=ppx_yo2ov_dt_b_product_details

{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}

**Comment by The-EG** [comment] 2023-03-05 13:02
Duplicate of #106

**Closed by The-EG** 2023-03-05 13:02 UTC
Labels: enhancement
