### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by AntonBock** [The-EG/OctoPrint-CameraSettings#156] opened 2023-04-17 08:20 UTC
**Raspberry Pi  Camera module 3**:

**{
  "wide_dynamic_range": {
    "type": "bool",
    "default": "0",
    "value": "0",
    "flags": "grabbed"
  }
}**:

**Comment by The-EG** [comment] 2023-04-17 13:38
duplicate of #100

**Closed by The-EG** 2023-04-17 13:38 UTC
Labels: enhancement
