### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by Bjoern112** [The-EG/OctoPrint-CameraSettings#159] opened 2023-04-23 06:55 UTC
**Camera manufacturer and model (ie. Angetube 925H HRF 60fps HD AF 1080P)**:

{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}

**Comment by The-EG** [comment] 2023-04-25 11:32
duplicate of #106 . I guess it's time to move that release candidate to release 😄

**Closed by The-EG** 2023-04-25 11:32 UTC
Labels: enhancement
