### ISSUE TITLE
[FR] Implement Controls for Hawkeye-64mp

### ISSUE THREAD

**Issue by EdJ1** [The-EG/OctoPrint-CameraSettings#144] opened 2023-03-29 20:27 UTC
Arducam Hawkeye-64mp

Followed these instructions: 
https://docs.arducam.com/Raspberry-Pi-Camera/Native-camera//64MP-Hawkeye
Camera is NOT working (Yet).

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}

**Comment by The-EG** [comment] 2023-04-06 23:13
The unknown controls should already be handled in the latest release candidate. If you do have specific issues for that camera, please open an issue with those details.

duplicate of #106

**Closed by The-EG** 2023-04-06 23:13 UTC
Labels: enhancement
