### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by KilonovaRemnant** [The-EG/OctoPrint-CameraSettings#148] opened 2023-04-04 03:32 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:
Logitech C920

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}

P.S. I have no idea why there is a problem with this camera and set up as it works brilliantly on my two other machines with the same setup. But, I’m submitting in case it helps. Thanks for the great plug-in!

**Comment by The-EG** [comment] 2023-04-06 23:12
thanks, this should already be in the release candidate and will go away when you install that version when released (or should at least!)

Duplicate of #106

**Closed by The-EG** 2023-04-06 23:12 UTC
Labels: enhancement
