### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by Lcharsh** [The-EG/OctoPrint-CameraSettings#63] opened 2021-12-01 23:40 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "force_key_frame": {
    "type": "button",
    "flags": "write"
  },
  "h264_minimum_qp_value": {
    "type": "int",
    "min": "0",
    "max": "51",
    "step": "1",
    "default": "0",
    "value": "0"
  },
  "h264_maximum_qp_value": {
    "type": "int",
    "min": "0",
    "max": "51",
    "step": "1",
    "default": "0",
    "value": "0"
  }
}

**Comment by The-EG** [comment] 2021-12-01 23:42
duplicate of #62 - please install the latest RC

**Closed by The-EG** 2021-12-01 23:42 UTC
Labels: duplicate, enhancement
