### ISSUE TITLE
[FR] Implement Controls for [Logitech C310 HD 720p USB Webcam}

### ISSUE THREAD

**Issue by d-nx** [The-EG/OctoPrint-CameraSettings#27] opened 2021-05-01 01:05 UTC
**Camera manufacturer and model (Logitech C310 HD 720p USB Webcam w/ Built in Microphone V-U0015)**:

**Unknown controls information:
{
  "led1_mode": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Off"
      },
      {
        "value": "1",
        "desc": "On"
      },
      {
        "value": "2",
        "desc": "Blink"
      },
      {
        "value": "3",
        "desc": "Auto"
      }
    ],
    "min": "0",
    "max": "3",
    "default": "3",
    "value": "3"
  },
  "led1_frequency": {
    "type": "int",
    "min": "0",
    "max": "131",
    "step": "1",
    "default": "0",
    "value": "0"
  }
}

**Comment by The-EG** [comment] 2021-05-01 08:09
Hi there, this is already included in the updated release that I just created, 0.1.1. You should be able to update to that now.

duplicate of #22

**Closed by The-EG** 2021-05-01 08:10 UTC
Labels: duplicate
