### ISSUE TITLE
[FR] Implement Controls for MakerFocus Raspberry Pi 4B Camera IR Camera Module 7

### ISSUE THREAD

**Issue by tdewar** [The-EG/OctoPrint-CameraSettings#130] opened 2023-03-17 15:03 UTC
**MakerFocus Raspberry Pi 4B Camera IR Camera Module 75 Degree 5MP OV5647 Webcam Automatically Switching Between Day and Night Vision with Holder and Cable for Raspberry Pi 4B 3B+ Zero and Zero W**:

**{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}**:

**Comment by The-EG** [comment] 2023-03-17 15:36
duplicate of #106

**Closed by The-EG** 2023-03-17 15:36 UTC
