### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by altcoin725** [The-EG/OctoPrint-CameraSettings#137] opened 2023-03-22 00:36 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "wide_dynamic_range": {
    "type": "bool",
    "default": "0",
    "value": "0",
    "flags": "modify"
  }
}

**Comment by The-EG** [comment] 2023-03-22 05:42
Duplicate of #100

**Closed** 2023-03-22 05:42 UTC
Labels: enhancement
