### ISSUE TITLE
[FR] Implement Controls for Raspberry Pi High Quality Camera

### ISSUE THREAD

**Issue by nitinab** [The-EG/OctoPrint-CameraSettings#176] opened 2023-05-20 09:56 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:

{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}

Kind of surprised that Raspberry Pi High Quality Camera is not supported, could this be due to my camera not being detected correctly ?

**Comment by The-EG** [comment] 2023-05-20 11:12
It is supported, this is just reporting that these specific controls are not recognized. This is already addressed in the latest release candidate. duplicate of #106

**Closed by The-EG** 2023-05-20 11:12 UTC
Labels: enhancement
