### ISSUE TITLE
[FR] Implement Controls for SVPRO Portable USB Camera with Sony IMX323 Sensor

### ISSUE THREAD

**Issue by omgseb** [The-EG/OctoPrint-CameraSettings#82] opened 2022-08-30 08:03 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:
"SVPRO Portable USB Camera 1080P Mini USB Web Camera with Aluminum Case, HD Camera with 170 Degree Lens Ultra Wide Angle, 0.01lux Low Light Camera with Sony IMX323 Sensor H.264 30fps"
https://www.amazon.com/dp/B07C1R7G5J

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
```
{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  },
  "hevc_decode_mode": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Slice-Based"
      }
    ],
    "min": "0",
    "max": "0",
    "default": "0",
    "value": "0"
  },
  "hevc_start_code": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "No Start Code"
      }
    ],
    "min": "0",
    "max": "0",
    "default": "0",
    "value": "0"
  }
}
```

I feel like that isn't enough data, but I'm not sure what else to provide. Happy to provide more with a little guidance.

**Comment by The-EG** [comment] 2022-08-30 11:47
I believe these have already been covered in the latest release candidate. You can try that out by selecting the 'Release Candidate' channel for this plugin in the OctoPrint Software Update settings and then updating to 0.4.1rc2.

Otherwise you'll get this once I release that as a production version. Duplicate of #76 and #70

**Closed by The-EG** 2022-08-30 11:47 UTC
Labels: enhancement
