### ISSUE TITLE
[FR] Implement Controls for BCC950 ConferenceCam

### ISSUE THREAD

**Issue by ksemel** [The-EG/OctoPrint-CameraSettings#61] opened 2021-11-14 21:47 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:

BCC950 ConferenceCam

Logitech Conference Video Conference Webcam, HD 1080p Camera with Built-In Speakerphone
(this one: https://smile.amazon.com/gp/product/B0083I7Y8W/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1)

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:

```
{
  "pan_relative": {
    "type": "int",
    "min": "-4480",
    "max": "4480",
    "step": "1",
    "default": "0",
    "value": "0"
  },
  "tilt_relative": {
    "type": "int",
    "min": "-1920",
    "max": "1920",
    "step": "1",
    "default": "0",
    "value": "10"
  },
  "pan_reset": {
    "type": "button",
    "flags": "write"
  },
  "tilt_reset": {
    "type": "button",
    "flags": "write"
  }
}
```

**Comment by The-EG** [comment] 2021-11-15 12:04
Duplicate of #42 and #46

I don't yet have a good way of adding relative controls. Ideally, ones like your tilt and pan here should have a slider or input that allows the user to specify the value and then buttons to actually make the change. And the current value is never known, hence the 'reset' buttons.

The problem here is that I don't have a device to test this out with. I may be able to snag one of my other webcams for testing soon, however.

**Closed** 2021-11-15 12:04 UTC
Labels: duplicate
