### ISSUE TITLE
[FR] Implement Controls for Anker PowerConf C200 Webcam

### ISSUE THREAD

**Issue by hiramknick** [The-EG/OctoPrint-CameraSettings#90] opened 2022-11-10 22:44 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:
Anker PowerConf c200 2k Webcam

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  },
  "hevc_decode_mode": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "Slice-Based"
      }
    ],
    "min": "0",
    "max": "0",
    "default": "0",
    "value": "0"
  },
  "hevc_start_code": {
    "type": "menu",
    "values": [
      {
        "value": "0",
        "desc": "No Start Code"
      }
    ],
    "min": "0",
    "max": "0",
    "default": "0",
    "value": "0"
  }
}

**Comment by The-EG** [comment] 2022-11-11 13:37
Hi there, these are already included in the latest pre-release. You can either install that version now or wait until I move it to a full release, which should happen in the next few days.

Duplicate of #76 and #70

**Closed by The-EG** 2022-11-11 13:37 UTC
Labels: enhancement
