### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by ebric47** [The-EG/OctoPrint-CameraSettings#157] opened 2023-04-17 17:37 UTC
**Camera manufacturer and model Cam023 Raspberry IR-CUT Camera Automatic Version)**:

**Unknown controls information ({
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
})**:

**Comment by The-EG** [comment] 2023-04-17 17:38
duplicate of #106

**Closed by The-EG** 2023-04-17 17:38 UTC
Labels: enhancement

**Comment by ebric47** [comment] 2023-04-17 17:50
Thanks, issue resolved Ed Brickey From: Taylor TalkingtonSent: Monday, April 17, 2023 1:38 PMTo: The-EG/OctoPrint-CameraSettingsCc: ebric47; AuthorSubject: Re: [The-EG/OctoPrint-CameraSettings] [FR] Implement Controls for [Camera Name] (Issue #157) duplicate of #106—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
