### ISSUE TITLE
Onebuy Webcam cheap Amazon webcam

### ISSUE THREAD

**Issue by Zardoz66** [The-EG/OctoPrint-CameraSettings#5] opened 2021-04-16 22:18 UTC
[octoprint-2.log](https://github.com/The-EG/OctoPrint-CameraSettings/files/6328089/octoprint-2.log)
no controls working also missing.

**Comment by The-EG** [comment] 2021-04-16 22:25
'also missing' as in missing controls? Please paste the data from the 'copy to clipboard' if so.

**Comment by The-EG** [comment] 2021-04-16 22:35
from discord chat: camera controls not missing, just don't work. this will be a duplicate of #4 I think.

**Closed by The-EG** 2021-04-16 22:35 UTC
Labels: need more info
