### ISSUE TITLE
[FR] Implement Controls for Raspi Cam V3 NoIR

### ISSUE THREAD

**Issue by Nomo1-7** [The-EG/OctoPrint-CameraSettings#117] opened 2023-03-07 13:44 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:
Raspi Cam V3 NoIR
{
  "wide_dynamic_range": {
    "type": "bool",
    "default": "0",
    "value": "0",
    "flags": "grabbed"
  }
}

**Comment by The-EG** [comment] 2023-03-15 18:03
duplicate of #100, this is already available in the latest release candidate.

**Closed by The-EG** 2023-03-15 18:03 UTC
Labels: enhancement
