### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by fungreenfox** [The-EG/OctoPrint-CameraSettings#110] opened 2023-02-18 13:26 UTC
Was asked by the interface to post this. The camera is from Tecknet. 
It can be listed at https://www.researchgate.net/figure/TeckNetR-C016-USB-HD-720P-Webcam-5-Megapixels-5G-Lenses-USB-Microphone-6-LED-One_fig4_319652760

**Camera manufacturer and model (ie. NexiGO N660)**:

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "hevc_sequence_parameter_set": {
    "type": "unknown"
  },
  "hevc_picture_parameter_set": {
    "type": "unknown"
  },
  "slice_param_array": {
    "type": "unknown"
  },
  "hevc_scaling_matrix": {
    "type": "unknown"
  },
  "hevc_decode_parameters": {
    "type": "unknown"
  }
}

**Comment by The-EG** [comment] 2023-02-26 15:22
Duplicate of #106 (unknown should already be ignored)

**Closed by The-EG** 2023-02-26 15:22 UTC
Labels: enhancement
