### ISSUE TITLE
[FR] Implement Controls for imx708_noir

### ISSUE THREAD

**Issue by EdJ1** [The-EG/OctoPrint-CameraSettings#164] opened 2023-04-27 16:59 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:
Raspberry pi V3
It is listed as imx708_noir

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "wide_dynamic_range": {
    "type": "bool",
    "default": "0",
    "value": "0",
    "flags": "grabbed"
  }
}

Thank you for supporting Octoprint!

**Comment by The-EG** [comment] 2023-04-27 17:47
duplicate of #100

**Closed by The-EG** 2023-04-27 17:47 UTC
Labels: enhancement
