### ISSUE TITLE
[FR] Implement Controls for [Camera Name]

### ISSUE THREAD

**Issue by EsherionM** [The-EG/OctoPrint-CameraSettings#66] opened 2022-01-10 23:33 UTC
**Camera manufacturer and model (ie. NexiGO N660)**:
Anpro Kamera für Raspberry Pi 3 Modell B + (Plus), 5 Megapixel Kamera mit 2 Ersatz Flexkabel 15 cm 100 cm, EINWEG

**Unknown controls information (click 'Copy to Clipboard' on the warning and paste here)**:
{
  "force_key_frame": {
    "type": "button",
    "flags": "write"
  },
  "h264_minimum_qp_value": {
    "type": "int",
    "min": "0",
    "max": "51",
    "step": "1",
    "default": "0",
    "value": "0"
  },
  "h264_maximum_qp_value": {
    "type": "int",
    "min": "0",
    "max": "51",
    "step": "1",
    "default": "0",
    "value": "0"
  }
}

**Comment by The-EG** [comment] 2022-01-11 12:21
duplicate of #62 

This is fixed in the latest release, 0.3.1.

**Closed by The-EG** 2022-01-11 12:21 UTC
Labels: enhancement
